
INSERT INTO SYS_MENUS (FORM_NAME, MENU_INDEX, MODULE_ID, MENU_ITEM_INDEX, FORM_CAPTION, ENABLED, UPDATE_DATE, UPDATE_USER, FORM_TAG, HISTORY_CAPTION, MAIN_MENU_NAME, REPORTID, QUERYSTRING) VALUES ('AR21', 2, 'AR', 1, 'AR Ledger Inquiry', 'Y', CURRENT_DATE, 'admin', 21, 'AR Ledger Inquiry', 'ARMENU', 'ARLedger.fr3', NULL);

INSERT INTO SYS_MENUS (FORM_NAME, MENU_INDEX, MODULE_ID, MENU_ITEM_INDEX, FORM_CAPTION, ENABLED, UPDATE_DATE, UPDATE_USER, FORM_TAG, HISTORY_CAPTION, MAIN_MENU_NAME, REPORTID, QUERYSTRING) VALUES ('AR23', 2, 'AR', 3, 'AR Outstanding Invoice', 'Y', CURRENT_DATE, 'admin', 23, 'AR Outstanding Invoice', 'ARMENU', 'AROUTSTANDING.fr3', NULL);

