

INSERT INTO SYS_MENUS (FORM_NAME, MENU_INDEX, MODULE_ID, MENU_ITEM_INDEX, FORM_CAPTION, ENABLED, UPDATE_DATE, UPDATE_USER, FORM_TAG, HISTORY_CAPTION, MAIN_MENU_NAME, REPORTID, QUERYSTRING) VALUES
('AP12', 1, 'AP', 2, 'AP Invoice Entry', 'Y', CURRENT_TIMESTAMP, 'admin', 11, 'AP Invoice Entry', 'APMENU', '', NULL);

